name: cocal_personal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.5
  path: ^1.9.0
  supabase_flutter: ^2.5.6
  dio: ^5.7.0
  connectivity_plus: ^6.0.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.3.2
  crypto: ^3.0.5
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  responsive_framework: ^1.2.0
  provider: ^6.1.2
  fluttertoast: ^8.2.6
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  intl: ^0.18.1
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.24
  flutter_launcher_icons: ^0.14.4  # <-- versiÃ³n arreglada

flutter:
  uses-material-design: true

  assets:
    - assets/icono_app.png

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icono_app.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icono_app.png"
